@echo off
REM Improved Setup script for wt (Git Worktree Helper)
REM This version creates an AutoRun script that loads automatically

echo === Git Worktree Helper (wt) Setup ===
echo.

REM Get the script directory
set SCRIPT_DIR=%~dp0
set WT_SCRIPT=%SCRIPT_DIR%wt.bat

REM Verify wt.bat exists
if not exist "%WT_SCRIPT%" (
    echo Error: wt.bat not found in %SCRIPT_DIR%
    pause
    exit /b 1
)

echo Installing wt command...
echo.

REM Create AutoRun script
set AUTORUN_DIR=%USERPROFILE%\.cmdrc
set AUTORUN_SCRIPT=%AUTORUN_DIR%\wt-alias.cmd

if not exist "%AUTORUN_DIR%" mkdir "%AUTORUN_DIR%"

echo @echo off > "%AUTORUN_SCRIPT%"
echo REM Auto-generated by wt setup >> "%AUTORUN_SCRIPT%"
echo doskey wt="%WT_SCRIPT%" $* >> "%AUTORUN_SCRIPT%"

echo ✓ Created AutoRun script at: %AUTORUN_SCRIPT%
echo.

REM Set AutoRun in registry
reg add "HKCU\Software\Microsoft\Command Processor" /v AutoRun /t REG_SZ /d "%AUTORUN_SCRIPT%" /f >nul 2>&1

if %ERRORLEVEL% EQU 0 (
    echo ✓ AutoRun configured successfully
    echo.
    echo === Setup Complete! ===
    echo.
    echo The 'wt' command will now be available in ALL new CMD windows.
    echo Please close this window and open a new CMD window.
    echo.
) else (
    echo × Failed to set AutoRun registry key
    echo.
    echo Manual setup required:
    echo 1. Run this command as Administrator, or
    echo 2. Add manually to registry:
    echo    HKEY_CURRENT_USER\Software\Microsoft\Command Processor
    echo    AutoRun = "%AUTORUN_SCRIPT%"
    echo.
)

echo For THIS window only, run: doskey wt="%WT_SCRIPT%" $*
echo.

pause
